SF = amblySubs.B1.Peripho.sfDistAE;
fileNames = [amblySubs.B1.Peripho.FEfiles'; amblySubs.B1.Peripho.AEfiles'];
[B1.hf,...
    amblySubs.B1.Peripho.FitParams,...
    amblySubs.B1.Peripho.ChisqGoodFit,...
    amblySubs.B1.Peripho.SpatialResolution,...
    amblySubs.B1.Peripho.aiTom] =...
    csf_amblyopesM(SF,fileNames);