XTCRIv1RE = XTV1.conRadRE.CRI;
XTCRIv1LE = XTV1.conRadLE.CRI;

XTCRIv4RE = XTV4.conRadRE.CRI;
XTCRIv4LE = XTV4.conRadLE.CRI;

WUCRIv1RE = WUV1.conRadRE.CRI;
WUCRIv1LE = WUV1.conRadLE.CRI;

WUCRIv4RE = WUV4.conRadRE.CRI;
WUCRIv4LE = WUV4.conRadLE.CRI;

WVCRIv1RE = WVV1.conRadRE.CRI;
WVCRIv1LE = WVV1.conRadLE.CRI;

WVCRIv4RE = WVV4.conRadRE.CRI;
WVCRIv4LE = WVV4.conRadLE.CRI;